name: scRFE
channels:
  - defaults
dependencies:
  - python = 3.6
  - pip=19.1.1
  - wheel=0.33.6=py36_0
  - pip:
    - numpy==1.16.4
    - pandas==0.24.2
    - anndata==0.6.21
    - scikit-learn==0.21.2
    - seaborn==0.9.0
    - scanpy==1.4.3
    - scipy==1.2.1
    - matplotlib==3.2.1
    - matplotlib-venn==0.11.5
    - setuptools==41.0.1
    - wheel==0.33.4
